import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { BackendApiContext, BackendApiService } from "@/lib/BackendApiService";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Scraping results",
  description: "Generated by scraping results.",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={inter.className}>{children}</body>
    </html>
  );
}
